PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  ?object ?name
WHERE
  { dbpr:Sri_Lankan_Civil_War
              ?predicate  ?object .
    ?object   rdfs:label  ?name
  }
