PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  ?object ?name
WHERE
  { <http://dbpedia.org/resource/United_Kingdom_general_election,_1987>
              ?predicate  ?object .
    ?object   rdfs:label  ?name
  }
