PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  ?object ?name
WHERE
  { <http://dbpedia.org/resource/L'Or%C3%A9al>
              ?predicate  ?object .
    ?object   rdfs:label  ?name
  }
