PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  ?object ?name
WHERE
  { <http://dbpedia.org/resource/Diego_Vel%C3%A1zquez>
              ?predicate  ?object .
    ?object   rdfs:label  ?name
  }
