PREFIX  dbpo: <http://dbpedia.org/ontology/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  ?Property ?Place
WHERE
  { dbpr:Barack_Obama
              ?Property  ?Place .
    ?Place    rdf:type   dbpo:Place
  }
