PREFIX  wde:  <http://www.wikidata.org/entity/>
PREFIX  dbpo: <http://dbpedia.org/ontology/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT  ?object
WHERE
  { ?s       dbpo:successor  ?object .
    ?object  rdf:type        wde:Q486839
  }
