PREFIX  dbpo: <http://dbpedia.org/ontology/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  ?Who
WHERE
  { ?Who      rdf:type     dbpo:Person .
    ?daughter  dbpo:spouse  ?Who .
    dbpr:Robert_F._Kennedy
              dbpo:child   ?daughter
  }
