PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  dbpo: <http://dbpedia.org/ontology/>

SELECT  ?companies
WHERE
  { ?companies  rdf:type     dbpo:Company .
    ?industry  dbpo:industry  ?companies
  }
