PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  cat:  <http://dbpedia.org/resource/Category:>

SELECT  ?broaderConcept ?preferredLabel
WHERE
  { cat:Manufacturing
              skos:broader    ?broaderConcept .
    ?broaderConcept
              skos:prefLabel  ?preferredLabel
  }
