PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  dct:  <http://purl.org/dc/terms/>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  ?o1
WHERE
  { dbpr:Empire_of_Lust
              dct:subject   ?o .
    ?o        skos:broader  ?o1
  }
