PREFIX  dbpo: <http://dbpedia.org/ontology/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>

SELECT  ?a ?f
WHERE
  { ?a  rdf:type       foaf:Person .
    ?f  dbpo:starring  ?a
  }
