PREFIX  dbpo: <http://dbpedia.org/ontology/>
PREFIX  dbpr: <http://dbpedia.org/resource/>
PREFIX  dbprop: <http://dbpedia.org/property/>

SELECT  *
WHERE
  { ?p  dbprop:team  ?t .
    ?t  dbpo:league  dbpr:Premier_League
  }
