PREFIX  :     <http://dbpedia.org/resource/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>

SELECT  *
WHERE
  { :Christopher_Evans
              foaf:isPrimaryTopicOf  ?x .
    ?x        ?y                    ?z
  }
