PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dct:  <http://purl.org/dc/terms/>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  ?cat
WHERE
  { <http://dbpedia.org/resource/Service_(economics)>
              dct:subject  ?subject .
    ?subject  rdfs:label   ?cat
  }
