# Sink-shaped query: Retrieve all employees of an organization
SELECT * WHERE {
  
    ?o1 <http://example.org/name> ?o2 .
    ?o1 <http://example.org/country> ?o3 .
    ?o1 <http://example.org/population> ?o4 .
 
}  
