PREFIX  pos:  <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX  dbprop: <http://dbpedia.org/property/>

SELECT  *
WHERE
  { ?airport  dbprop:name  ?name ;
              dbprop:iata  ?iata_code ;
              dbprop:icao  ?icao_code ;
              pos:lat      ?latitude ;
              pos:long     ?longitude
  }
