PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  dbpo: <http://dbpedia.org/ontology/>

SELECT  *
WHERE
  { ?DBpediaInstitution
              rdf:type              dbpo:University ;
              dbpo:wikiPageID       ?PageID_2 ;
              dbpo:numberOfStudents  ?City ;
              dbpo:viceChancellor   ?VC
  }
