PREFIX  dbpo: <http://dbpedia.org/ontology/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  *
WHERE
  { ?person  dbpo:series      dbpr:The_Big_Bang_Theory ;
             rdf:type         dbpo:FictionalCharacter ;
             dbpo:occupation  ?occ
  }
