PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dbpo: <http://dbpedia.org/ontology/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT  ?f ?l ?a
WHERE
  { ?f  rdf:type       dbpo:Film ;
        rdfs:label     ?l ;
        dbpo:abstract  ?a
  }
