PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  dbprop: <http://dbpedia.org/property/>

SELECT  ?book ?genre
WHERE
  { ?book  dbprop:name       "The Catcher in the Rye"@en ;
           dbprop:genre      ?genre ;
           dbprop:publisher  ?pub
  }
