PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  dbpo: <http://dbpedia.org/ontology/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  dbprop: <http://dbpedia.org/property/>

SELECT  ?film ?abstract ?editor ?producer ?comment
WHERE
  { ?film  dbprop:name    "She's Gotta Have It"@en ;
           dbpo:abstract  ?abstract ;
           dbpo:producer  ?producer ;
           dbpo:editing   ?editor ;
           rdfs:comment   ?comment
  }
