PREFIX  dbpo: <http://dbpedia.org/ontology/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  ?p
WHERE
  { ?s       ?p                dbpr:George_Orwell .
    ?author  rdf:type          dbpo:Writer ;
             dbpo:notableWork  ?work
  }
