PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  dbpo: <http://dbpedia.org/ontology/>

SELECT  *
WHERE
  { ?p        rdf:type         dbpo:Person ;
              dbpo:influenced  ?influenced .
    ?influenced  rdf:type      dbpo:Person
  }
