PREFIX  :     <http://dbpedia.org/resource/>
PREFIX  dbpo: <http://dbpedia.org/ontology/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT  ?squadra ?stadio
WHERE
  { ?squadra  rdf:type     dbpo:SoccerClub ;
              dbpo:league  :La_Liga ;
              dbpo:ground  ?stadio
  }
