PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  *
WHERE
  { dbpr:Brazil  ?p1  ?r2 .
    ?r2       ?p2  ?r3 .
    ?r3       ?p3  ?r4 .
    dbpr:Brazil  ?p1  ?r6 .
    ?r6       ?p2  ?r7 .
    ?r7       ?p3  ?r8
  }
