PREFIX  dbpr: <http://dbpedia.org/resource/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>

SELECT  *
WHERE
  { dbpr:Paul_McGann
              foaf:name  ?name1 .
    dbpr:Vincent_Pérez
              foaf:name  ?name2
  }
