PREFIX  dbpr: <http://dbpedia.org/resource/>
PREFIX  dbprop: <http://dbpedia.org/property/>

SELECT  ?BirthPlace
WHERE
  { ?BirthPlace  dbprop:birthPlace  dbpr:Belgium .
    ?DeathPlace  dbprop:deathPlace  dbpr:Belgium
  }
