PREFIX  :     <http://dbpedia.org/resource/>
PREFIX  dbprop: <http://dbpedia.org/property/>

SELECT  ?player
WHERE
  { ?player  dbprop:clubs  <http://dbpedia.org/resource/Beitar_Jerusalem_F.C.> ;
             dbprop:clubs  <http://dbpedia.org/resource/Hapoel_Tel_Aviv_F.C.>
  }
