PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  dbpo: <http://dbpedia.org/ontology/>

SELECT  *
WHERE
  { ?person   rdf:type  dbpo:IceHockeyPlayer .
    ?birthPlace  rdf:type  dbpo:IceHockeyPlayer
  }
