PREFIX  :     <http://dbpedia.org/resource/>
PREFIX  dbpo: <http://dbpedia.org/ontology/>

SELECT  ?person ?c
WHERE
  { :Albert_Einstein
              dbpo:citizenship  ?c .
    ?person   dbpo:citizenship  ?c
  }
