PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX  dct:  <http://purl.org/dc/terms/>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  ?nadcateg ?categ
WHERE
  { dbpr:Smart_grid
              dct:subject   ?categ .
    ?nadcateg  skos:broader  ?categ
  }
