PREFIX  :     <http://dbpedia.org/resource/>
PREFIX  dbprop: <http://dbpedia.org/property/>

SELECT  ?player
WHERE
  { ?player  dbprop:clubs  <http://dbpedia.org/resource/Manchester_United_F.C.> ;
             dbprop:clubs  <http://dbpedia.org/resource/Real_Madrid_C.F.>
  }
