PREFIX  :     <http://dbpedia.org/resource/>
PREFIX  dbprop: <http://dbpedia.org/property/>

SELECT  ?player
WHERE
  { ?player  dbprop:clubs  :Inter_Milan ;
             dbprop:clubs  :FC_Barcelona
  }
