PREFIX  dbpr: <http://dbpedia.org/resource/>
PREFIX  dbpo: <http://dbpedia.org/ontology/>

SELECT  ?films
WHERE
  { ?films  dbpo:starring  dbpr:Richard_Gere ;
            dbpo:starring  dbpr:Julia_Roberts
  }
