PREFIX  dbpr: <http://dbpedia.org/resource/>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>

SELECT  *
WHERE
  { dbpr:Anthony_Rapp
              foaf:name  ?name1 .
    dbpr:Jennifer_Connelly
              foaf:name  ?name2
  }
