PREFIX  dbpo: <http://dbpedia.org/ontology/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  foaf: <http://xmlns.com/foaf/0.1/>
PREFIX  dbpr: <http://dbpedia.org/resource/>

SELECT  ?s
WHERE
  { ?s  rdf:type         foaf:Person ;
        rdf:type         dbpo:MusicalArtist ;
        dbpo:birthPlace  dbpr:South_Korea
  }
